### ISSUE TITLE
how to set config parameters?

### ISSUE THREAD

**Issue by hotarujun** [bwconrad/vit-finetune#9]
Hello,

  Thank you so much for sharing the code ! 

  I'm training custom data with your code, the dataset is [525 bird images](https://www.kaggle.com/datasets/gpiosenka/100-bird-species). But I don't know how these parameters should be set. Here's my configuration file:

```
trainer:
  accelerator: gpu
  devices: 2
  precision: 16-mixed
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: /kaggle/working/
      name: custom
  max_steps: 5000
  val_check_interval: 500
model:
  model_name: vit-b16-224-in21k
  training_mode: full
  optimizer: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
data:
  dataset: custom
  root: /kaggle/input/100-bird-species
  num_classes: 525
  size: 224
  batch_size: 64
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max
```

  At about the 7th epoch, the training was abruptly stopped, it may be related to the **max_steps** parameter. So in this case, how should I set the appropriate parameters to complete the full training task ? I would appreciate it if you could give me some specific data.
